### ISSUE TITLE
Error in loading `baxter.urdf.xacro` onto parameter server

### ISSUE THREAD

**Issue by alecive** [RethinkRobotics/baxter_common#83]
Hello, I am trying to load `baxter.urdf.xacro` in the parameter server without running the robot (for testing purposes).

To this end, I created the following file (please tell me if it can be improved):

```
<launch>
  <param name="robot_description" command="$(find xacro)/xacro '$(find baxter_description)/urdf/baxter.urdf.xacro'" />
</launch>
```

But when I run it, I get the following error: 

```
[alecive@malakim]$ roslaunch baxter_react_controller baxter_urdf.launch 
... logging to /home/alecive/.ros/log/6277adee-ed81-11e6-8593-6c2995068b46/roslaunch-malakim-21423.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traceback (most recent call last):
  File "/home/alecive/code/ros_catkin_ws/install_isolated/lib/xacro/xacro", line 55, in <module>
    xacro.main()
  File "/home/alecive/code/ros_catkin_ws/install_isolated/lib/python2.7/dist-packages/xacro/__init__.py", line 687, in main
    process_includes(doc, os.path.dirname(args[0]))
  File "/home/alecive/code/ros_catkin_ws/install_isolated/lib/python2.7/dist-packages/xacro/__init__.py", line 246, in process_includes
    filename_spec = eval_text(elt.getAttribute('filename'), {})
  File "/home/alecive/code/ros_catkin_ws/install_isolated/lib/python2.7/dist-packages/xacro/__init__.py", line 483, in eval_text
    results.append(handle_expr(lex.next()[1][2:-1]))
  File "/home/alecive/code/ros_catkin_ws/install_isolated/lib/python2.7/dist-packages/xacro/__init__.py", line 470, in handle_expr
    return eval_expr(lex, symbols)
  File "/home/alecive/code/ros_catkin_ws/install_isolated/lib/python2.7/dist-packages/xacro/__init__.py", line 444, in eval_expr
    result = eval_term(lex, symbols)
  File "/home/alecive/code/ros_catkin_ws/install_isolated/lib/python2.7/dist-packages/xacro/__init__.py", line 418, in eval_term
    result = eval_factor(lex, symbols)
  File "/home/alecive/code/ros_catkin_ws/install_isolated/lib/python2.7/dist-packages/xacro/__init__.py", line 398, in eval_factor
    return neg * eval_lit(lex, symbols)
  File "/home/alecive/code/ros_catkin_ws/install_isolated/lib/python2.7/dist-packages/xacro/__init__.py", line 369, in eval_lit
    raise XacroException("Property wasn't defined: %s" % str(ex))
xacro.XacroException: Property wasn't defined: u'l_finger'
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/home/alecive/code/ros_catkin_ws/install_isolated/lib/xacro/xacro '/home/alecive/code/catkin_ws/src/baxter_common/baxter_description/urdf/baxter.urdf.xacro'] returned with code [1]. 

Param xml is <param command="$(find xacro)/xacro '$(find baxter_description)/urdf/baxter.urdf.xacro'" name="robot_description"/>
The traceback for the exception was written to the log file
```

**Comment by IanTheEngineer** [comment]
you'll need to use the `--inorder` option when invoking `xacro` for it to run properly with the electric grippers.

**Comment by alecive** [comment]
Thank you!
